Repository Sylius/RefundPlugin, pull requests merged in 2018-07, with the labels that each got.

#1 Refunding single order unit scenarios
  features/refunding_single_order_unit.feature
  features/refunding_single_order_unit_with_promotion_applied.feature
  features/refunding_single_order_unit_with_taxes_applied.feature
  tests/Application/app/AppKernel.php
Labels: feature

#2 Refunds list implementation
  .travis.yml
  README.md
  features/refunding_single_order_unit.feature
  src/Action/OrderRefundsListAction.php
  src/DependencyInjection/Configuration.php
  src/Resources/config/app/config.yml
  src/Resources/config/app/routing.yml
  src/Resources/config/services.xml
  src/Resources/translations/messages.en.yml
  src/Resources/views/orderRefunds.html.twig
  src/SyliusRefundPlugin.php
  tests/Application/app/AppKernel.php
  tests/Application/app/config/config.yml
  tests/Application/app/config/routing.yml
  tests/Application/app/config/routing_dev.yml
  tests/Behat/Context/RefundingContext.php
  tests/Behat/Page/OrderRefundsPage.php
  tests/Behat/Page/OrderRefundsPageInterface.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites.yml
Labels: feature

#4 Refunding single unit
  README.md
  composer.json
  easy-coding-standard.yml
  features/refunding_single_order_unit.feature
  migrations/Version20180704112314.php
  phpspec.yml.dist
  spec/Checker/UnitRefundingAvailabilityCheckerSpec.php
  spec/Command/RefundUnitsSpec.php
  spec/CommandHandler/RefundUnitsHandlerSpec.php
  spec/Creator/RefundCreatorSpec.php
  spec/Entity/RefundSpec.php
  spec/Event/UnitRefundedSpec.php
  spec/Event/UnitsRefundedSpec.php
  spec/Factory/RefundFactorySpec.php
  spec/Listener/UnitsRefundedEventListenerSpec.php
  spec/Provider/OrderRefundedTotalProviderSpec.php
  spec/Provider/RefundedUnitTotalProviderSpec.php
  src/Action/RefundUnitsAction.php
  src/Checker/UnitRefundingAvailabilityChecker.php
  src/Checker/UnitRefundingAvailabilityCheckerInterface.php
  src/Command/RefundUnits.php
  src/CommandHandler/RefundUnitsHandler.php
  src/Creator/RefundCreator.php
  src/Creator/RefundCreatorInterface.php
  src/Entity/Refund.php
  src/Entity/RefundInterface.php
  src/Event/UnitRefunded.php
  src/Event/UnitsRefunded.php
  src/Exception/UnitAlreadyRefundedException.php
  src/Factory/RefundFactory.php
  src/Factory/RefundFactoryInterface.php
  src/Listener/UnitsRefundedEventListener.php
  src/Provider/OrderRefundedTotalProvider.php
  src/Provider/OrderRefundedTotalProviderInterface.php
  src/Provider/RefundedUnitTotalProvider.php
  src/Provider/RefundedUnitTotalProviderInterface.php
  src/Request/RefundUnitsRequest.php
  src/Resources/config/app/config.yml
  src/Resources/config/doctrine/Refund.orm.xml
  src/Resources/config/routing.yml
  src/Resources/config/services.xml
  src/Resources/config/services/actions.xml
  src/Resources/config/services/command_bus.xml
  src/Resources/config/services/event_bus.xml
  src/Resources/translations/flashes.en.yml
  src/Resources/translations/messages.en.yml
  src/Resources/views/orderRefunds.html.twig
  src/Twig/OrderRefundsExtension.php
  tests/Application/app/AppKernel.php
  tests/Application/app/config/routing.yml
  tests/Behat/Context/Application/RefundingContext.php
  tests/Behat/Context/RefundingContext.php
  tests/Behat/Context/Ui/RefundingContext.php
  tests/Behat/Page/OrderRefundsPage.php
  tests/Behat/Page/OrderRefundsPageInterface.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites.yml
Labels: feature

#5 Fix migration
  migrations/Version20180704112314.php
Labels: bug

#6 Add missing refunds button to order show page
  src/Menu/OrderShowMenuListener.php
  src/Resources/config/services.xml
Labels: enhancement

#7 Fix migration FOR REAL
  migrations/Version20180704112314.php
Labels: bug

#9 Enable refunding units with promotion and taxes scenarios
  features/refunding_single_order_unit_with_promotion_applied.feature
  features/refunding_single_order_unit_with_taxes_applied.feature
  tests/Behat/Resources/suites.yml
Labels: enhancement

#10 Refund all order units
  features/refunding_all_order_units.feature
  src/Resources/translations/messages.en.yml
  src/Resources/views/orderRefunds.html.twig
  tests/Behat/Context/Ui/RefundingContext.php
  tests/Behat/Page/OrderRefundsPage.php
  tests/Behat/Page/OrderRefundsPageInterface.php
Labels: feature

#12 Check validation of already refunded unit refund command
  features/refunding_single_order_unit.feature
  tests/Behat/Context/Setup/RefundingContext.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites.yml
Labels: enhancement

#11 Being able to refund units only from paid orders
  features/refunding_all_order_units.feature
  features/refunding_single_order_unit.feature
  features/refunding_single_order_unit_with_promotion_applied.feature
  features/refunding_single_order_unit_with_taxes_applied.feature
  spec/Checker/OrderRefundingAvailabilityCheckerSpec.php
  spec/CommandHandler/RefundUnitsHandlerSpec.php
  src/Action/OrderRefundsListAction.php
  src/Checker/OrderRefundingAvailabilityChecker.php
  src/Checker/OrderRefundingAvailabilityCheckerInterface.php
  src/CommandHandler/RefundUnitsHandler.php
  src/Exception/OrderNotAvailableForRefundingException.php
  src/Menu/OrderShowMenuListener.php
  src/Resources/config/services.xml
  src/Resources/config/services/actions.xml
  src/Resources/config/services/command_bus.xml
  src/Resources/translations/flashes.en.yml
  tests/Behat/Context/Ui/ManagingOrdersContext.php
  tests/Behat/Context/Ui/RefundingContext.php
  tests/Behat/Page/Order/ShowPage.php
  tests/Behat/Page/Order/ShowPageInterface.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites.yml
Labels: enhancement

#14 Add missing back button to refunds page
  features/refunding_single_order_unit.feature
  src/Resources/views/orderRefunds.html.twig
  tests/Behat/Context/Ui/RefundingContext.php
  tests/Behat/Page/OrderRefundsPage.php
  tests/Behat/Page/OrderRefundsPageInterface.php
Labels: enhancement

#13 Refunding order shipping
  .travis.yml
  features/refunding_all_order_units.feature
  features/refunding_order_shipping_cost.feature
  features/refunding_single_order_unit.feature
  features/refunding_single_order_unit_with_promotion_applied.feature
  features/refunding_single_order_unit_with_taxes_applied.feature
  migrations/Version20180718125528.php
  spec/Checker/UnitRefundingAvailabilityCheckerSpec.php
  spec/Command/RefundUnitsSpec.php
  spec/CommandHandler/RefundUnitsHandlerSpec.php
  spec/Creator/RefundCreatorSpec.php
  spec/Entity/RefundSpec.php
  spec/Event/ShipmentRefundedSpec.php
  spec/Event/UnitsRefundedSpec.php
  spec/Factory/RefundFactorySpec.php
  spec/Listener/UnitsRefundedEventListenerSpec.php
  spec/Provider/OrderRefundedTotalProviderSpec.php
  spec/Provider/RefundedShipmentFeeProviderSpec.php
  spec/Refunder/OrderItemUnitsRefunderSpec.php
  spec/Refunder/OrderShipmentsRefunderSpec.php
  src/Action/OrderRefundsListAction.php
  src/Checker/UnitRefundingAvailabilityChecker.php
  src/Checker/UnitRefundingAvailabilityCheckerInterface.php
  src/Command/RefundUnits.php
  src/CommandHandler/RefundUnitsHandler.php
  src/Creator/RefundCreator.php
  src/Creator/RefundCreatorInterface.php
  src/Entity/Refund.php
  src/Entity/RefundInterface.php
  src/Event/ShipmentRefunded.php
  src/Event/UnitsRefunded.php
  src/Exception/RefundTypeNotResolved.php
  src/Factory/RefundFactory.php
  src/Factory/RefundFactoryInterface.php
  src/Model/RefundType.php
  src/Provider/OrderRefundedTotalProvider.php
  src/Provider/RefundedShipmentFeeProvider.php
  src/Provider/RefundedShipmentFeeProviderInterface.php
  src/Refunder/OrderItemUnitsRefunder.php
  src/Refunder/OrderShipmentsRefunder.php
  src/Refunder/RefunderInterface.php
  src/Request/RefundUnitsRequest.php
  src/Resources/config/doctrine/Refund.orm.xml
  src/Resources/config/services.xml
  src/Resources/config/services/command_bus.xml
  src/Resources/translations/flashes.en.yml
  src/Resources/views/orderRefunds.html.twig
  src/Twig/OrderRefundsExtension.php
  tests/Behat/Context/Application/RefundingContext.php
  tests/Behat/Context/Setup/RefundingContext.php
  tests/Behat/Context/Ui/RefundingContext.php
  tests/Behat/Page/OrderRefundsPage.php
  tests/Behat/Page/OrderRefundsPageInterface.php
Labels: feature

#20 CreditMemo details table fix
  src/Resources/views/Order/Admin/CreditMemo/details.html.twig
Labels: bug

#23 Credit memo list bug fixes
  src/Resources/views/Order/Admin/CreditMemo/list.html.twig
Labels: bug
