Repository Sylius/RefundPlugin, pull requests merged in 2018-08, with the labels that each got.

#25 Browsing list of all credit memos
  features/browsing_list_of_all_credit_memos.feature
  spec/Entity/CreditMemoSpec.php
  src/Action/CreditMemoDetailsAction.php
  src/Action/OrderCreditMemosListAction.php
  src/Entity/CreditMemoInterface.php
  src/Menu/AdminMainMenuListener.php
  src/Menu/OrderShowMenuListener.php
  src/Resources/config/admin_routing.yml
  src/Resources/config/app/config.yml
  src/Resources/config/routing.yml
  src/Resources/config/services.xml
  src/Resources/config/services/actions.xml
  src/Resources/config/services/command_bus.xml
  src/Resources/translations/messages.en.yml
  src/Resources/views/Order/Admin/CreditMemo/_header.html.twig
  src/Resources/views/Order/Admin/CreditMemo/details.html.twig
  src/Resources/views/Order/Admin/CreditMemo/list.html.twig
  src/Resources/views/orderRefunds.html.twig
  tests/Behat/Context/Setup/RefundingContext.php
  tests/Behat/Context/Ui/CreditMemoContext.php
  tests/Behat/Page/CreditMemoIndexPage.php
  tests/Behat/Page/CreditMemoIndexPageInterface.php
  tests/Behat/Resources/services.xml
Labels: feature

#29 Send credit memo to customer automatically
  .travis.yml
  features/having_credit_memo_sent_to_customer.feature
  phpunit.xml.dist
  spec/Generator/CreditMemoGeneratorSpec.php
  spec/Listener/CreditMemoGeneratedEventListenerSpec.php
  spec/Sender/CreditMemoEmailSenderSpec.php
  src/Exception/CreditMemoNotFound.php
  src/Exception/OrderNotFound.php
  src/File/FileManagerInterface.php
  src/File/TemporaryFileManager.php
  src/Generator/CreditMemoGenerator.php
  src/Listener/CreditMemoGeneratedEventListener.php
  src/Resources/config/app/config.yml
  src/Resources/config/services.xml
  src/Resources/config/services/event_bus.xml
  src/Resources/views/Email/unitsRefunded.html.twig
  src/Sender/CreditMemoEmailSender.php
  src/Sender/CreditMemoEmailSenderInterface.php
  tests/Application/.gitignore
  tests/Behat/Context/Application/RefundingContext.php
  tests/Behat/Resources/services.xml
  tests/Unit/TemporaryFileManagerTest.php
Labels: feature

#30 I want to view a list of credit memos of any of my orders
  features/seeing_credit_memos_on_customer_order_view.feature
  migrations/Version20180725111447.php
  migrations/Version20180807090825.php
  spec/Entity/CreditMemoSpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  src/Entity/CreditMemo.php
  src/Generator/CreditMemoGenerator.php
  src/Resources/config/doctrine/CreditMemo.orm.xml
  src/Resources/config/routing.yml
  src/Resources/config/services.xml
  src/Resources/config/shop_routing.yml
  src/Resources/views/Order/Shop/_creditMemos.html.twig
  src/Resources/views/Order/Shop/creditMemos.html.twig
  tests/Behat/Context/Application/CreditMemoContext.php
  tests/Behat/Context/Ui/CreditMemoContext.php
  tests/Behat/Context/Ui/ManagingOrdersContext.php
  tests/Behat/Context/Ui/RefundingContext.php
  tests/Behat/Context/Ui/Shop/Customer/CreditMemosContext.php
  tests/Behat/Page/Admin/CreditMemoDetailsPage.php
  tests/Behat/Page/Admin/CreditMemoDetailsPageInterface.php
  tests/Behat/Page/Admin/CreditMemoIndexPage.php
  tests/Behat/Page/Admin/CreditMemoIndexPageInterface.php
  tests/Behat/Page/Admin/Order/ShowPage.php
  tests/Behat/Page/Admin/Order/ShowPageInterface.php
  tests/Behat/Page/Admin/OrderRefundsPage.php
  tests/Behat/Page/Admin/OrderRefundsPageInterface.php
  tests/Behat/Page/Shop/Order/ShowPage.php
  tests/Behat/Page/Shop/Order/ShowPageInterface.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites.yml
Labels: feature

#38 Make build great again
  .env.test.dist
  .gitignore
  .travis.yml
  features/browsing_list_of_all_credit_memos.feature
  features/downloading_credit_memo_as_pdf_file.feature
  features/downloading_credit_memo_on_customer_order_view.feature
  features/having_credit_memo_generated.feature
  features/seeing_credit_memos_on_customer_order_view.feature
  migrations/Version20180820132147.php
  spec/Entity/RefundPaymentSpec.php
  spec/Factory/RefundPaymentFactorySpec.php
  spec/Listener/UnitsRefundedEventListenerSpec.php
  spec/StateResolver/RefundPaymentCompletedStateApplierSpec.php
  src/Action/Admin/OrderRefundsListAction.php
  src/Action/Shop/DownloadCreditMemoAction.php
  src/Entity/RefundPayment.php
  src/Entity/RefundPaymentInterface.php
  src/Factory/RefundPaymentFactory.php
  src/Factory/RefundPaymentFactoryInterface.php
  src/File/TemporaryFileManager.php
  src/Listener/UnitsRefundedEventListener.php
  src/Resources/config/doctrine/RefundPayment.orm.xml
  src/Resources/config/services/event_bus.xml
  src/Resources/views/Order/Admin/RefundPayment/list.html.twig
  tests/Application/app/config/config.yml
  tests/Application/app/config/routing.yml
  tests/Behat/Context/Application/RefundingContext.php
  tests/Behat/Context/Setup/RefundingContext.php
  tests/Behat/Context/Ui/RefundingContext.php
Labels: bug

#39 Refund payment completed notification
  features/completing_refund_payment.feature
  src/Resources/translations/flashes.en.yml
  tests/Behat/Context/Ui/ManagingOrdersContext.php
Labels: bug

#42 Comment on credit memo
  features/providing_comment_for_credit_memo.feature
  migrations/Version20180821123925.php
  spec/Command/GenerateCreditMemoSpec.php
  spec/Command/RefundUnitsSpec.php
  spec/CommandHandler/GenerateCreditMemoHandlerSpec.php
  spec/CommandHandler/RefundUnitsHandlerSpec.php
  spec/Entity/CreditMemoSpec.php
  spec/Event/UnitsRefundedSpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  spec/Listener/UnitsRefundedEventListenerSpec.php
  spec/ProcessManager/CreditMemoProcessManagerSpec.php
  src/Command/GenerateCreditMemo.php
  src/Command/RefundUnits.php
  src/CommandHandler/GenerateCreditMemoHandler.php
  src/CommandHandler/RefundUnitsHandler.php
  src/Entity/CreditMemo.php
  src/Entity/CreditMemoInterface.php
  src/Event/UnitsRefunded.php
  src/Generator/CreditMemoGenerator.php
  src/Generator/CreditMemoGeneratorInterface.php
  src/ProcessManager/CreditMemoProcessManager.php
  src/Request/RefundUnitsRequest.php
  src/Resources/config/doctrine/CreditMemo.orm.xml
  src/Resources/views/Download/creditMemo.html.twig
  src/Resources/views/Order/Admin/CreditMemo/details.html.twig
  src/Resources/views/orderRefunds.html.twig
  tests/Behat/Context/Application/CreditMemoContext.php
  tests/Behat/Context/Application/RefundingContext.php
  tests/Behat/Context/Setup/RefundingContext.php
  tests/Behat/Context/Ui/CreditMemoContext.php
  tests/Behat/Context/Ui/RefundingContext.php
  tests/Behat/Page/Admin/CreditMemoDetailsPage.php
  tests/Behat/Page/Admin/CreditMemoDetailsPageInterface.php
  tests/Behat/Page/Admin/OrderRefundsPage.php
  tests/Behat/Page/Admin/OrderRefundsPageInterface.php
Labels: feature

#44 Improve refund payment method select
  src/Resources/views/orderRefunds.html.twig
Labels: UI

#43 Add authors and LICENSE file
  LICENSE
  composer.json
Labels: Maintenance

#45 Channel on credit memo
  features/browsing_list_of_all_credit_memos.feature
  features/having_credit_memo_generated.feature
  spec/Entity/CreditMemoChannelSpec.php
  spec/Entity/CreditMemoSpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  src/Entity/CreditMemo.php
  src/Entity/CreditMemoChannel.php
  src/Entity/CreditMemoInterface.php
  src/Generator/CreditMemoGenerator.php
  src/Resources/config/app/config.yml
  src/Resources/config/doctrine/CreditMemo.orm.xml
  src/Resources/config/doctrine/CreditMemoChannel.orm.xml
  src/Resources/translations/messages.en.yml
  src/Resources/views/Order/Admin/CreditMemo/_header.html.twig
  src/Resources/views/Order/Admin/CreditMemo/list.html.twig
  tests/Behat/Context/Application/CreditMemoContext.php
  tests/Behat/Context/Ui/CreditMemoContext.php
  tests/Behat/Page/Admin/CreditMemoDetailsPage.php
  tests/Behat/Page/Admin/CreditMemoDetailsPageInterface.php
  tests/Behat/Page/Admin/CreditMemoIndexPage.php
  tests/Behat/Page/Admin/CreditMemoIndexPageInterface.php
Labels: feature

#47 Order unit partial refund preparation
  .travis.yml
  features/refunding_part_of_order_unit.feature
  spec/Command/GenerateCreditMemoSpec.php
  spec/Command/RefundUnitsSpec.php
  spec/CommandHandler/GenerateCreditMemoHandlerSpec.php
  spec/CommandHandler/RefundUnitsHandlerSpec.php
  spec/Creator/RefundUnitsCommandCreatorSpec.php
  spec/Event/UnitsRefundedSpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  spec/Generator/OrderItemUnitCreditMemoUnitGeneratorSpec.php
  spec/Listener/UnitsRefundedEventListenerSpec.php
  spec/Model/UnitRefundSpec.php
  spec/ProcessManager/CreditMemoProcessManagerSpec.php
  spec/Provider/RefundedUnitTotalProviderSpec.php
  spec/Provider/RemainingOrderItemUnitTotalProviderSpec.php
  spec/Refunder/OrderItemUnitsRefunderSpec.php
  src/Action/Admin/RefundUnitsAction.php
  src/Command/GenerateCreditMemo.php
  src/Command/RefundUnits.php
  src/CommandHandler/GenerateCreditMemoHandler.php
  src/CommandHandler/RefundUnitsHandler.php
  src/Creator/CommandCreatorInterface.php
  src/Creator/RefundUnitsCommandCreator.php
  src/Event/UnitsRefunded.php
  src/Generator/CreditMemoGenerator.php
  src/Generator/CreditMemoGeneratorInterface.php
  src/Generator/CreditMemoUnitGeneratorInterface.php
  src/Generator/OrderItemUnitCreditMemoUnitGenerator.php
  src/Generator/ShipmentCreditMemoUnitGenerator.php
  src/Model/UnitRefund.php
  src/ProcessManager/CreditMemoProcessManager.php
  src/Provider/RefundedUnitTotalProvider.php
  src/Provider/RefundedUnitTotalProviderInterface.php
  src/Provider/RemainingOrderItemUnitTotalProvider.php
  src/Provider/RemainingTotalProviderInterface.php
  src/Refunder/OrderItemUnitsRefunder.php
  src/Refunder/OrderShipmentsRefunder.php
  src/Refunder/RefunderInterface.php
  src/Request/RefundUnitsRequest.php
  src/Resources/config/services.xml
  src/Resources/config/services/actions.xml
  src/Resources/config/services/provider.xml
  src/Resources/views/orderRefunds.html.twig
  tests/Behat/Context/Application/RefundingContext.php
  tests/Behat/Context/Setup/RefundingContext.php
  tests/Behat/Context/Ui/RefundingContext.php
Labels: enhancement

#49 Update Sylius configuration
  tests/Application/app/config/config.yml
  tests/Application/app/config/routing.yml
Labels: Maintenance

#46 Filtering credit memos
  features/filtering_credit_memos.feature
  migrations/Version20180826122832.php
  src/Form/Type/ChannelFilterType.php
  src/Grid/Filter/ChannelFilter.php
  src/Resources/config/app/config.yml
  src/Resources/config/services.xml
  src/Resources/views/Grid/Filter/channel.html.twig
  tests/Behat/Context/Setup/OrderContext.php
  tests/Behat/Context/Setup/RefundingContext.php
  tests/Behat/Context/Ui/CreditMemoContext.php
  tests/Behat/Page/Admin/CreditMemoIndexPage.php
  tests/Behat/Page/Admin/CreditMemoIndexPageInterface.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites.yml
Labels: feature

#48 Order unit partial refund
  features/having_credit_memo_generated.feature
  features/refunding_part_of_order_unit.feature
  migrations/Version20180829090832.php
  spec/Checker/UnitRefundingAvailabilityCheckerSpec.php
  spec/Creator/RefundCreatorSpec.php
  spec/Creator/RefundUnitsCommandCreatorSpec.php
  spec/Provider/UnitRefundedTotalProviderSpec.php
  src/Checker/UnitRefundingAvailabilityChecker.php
  src/Creator/RefundCreator.php
  src/Creator/RefundUnitsCommandCreator.php
  src/Exception/UnitRefundExceededException.php
  src/Model/RefundType.php
  src/Provider/UnitRefundedTotalProvider.php
  src/Provider/UnitRefundedTotalProviderInterface.php
  src/Resources/config/doctrine/Refund.orm.xml
  src/Resources/config/services.xml
  src/Resources/config/services/provider.xml
  src/Resources/translations/flashes.en.yml
  src/Resources/translations/messages.en.yml
  src/Resources/views/orderRefunds.html.twig
  src/Twig/OrderRefundsExtension.php
  tests/Behat/Context/Application/RefundingContext.php
  tests/Behat/Context/Setup/RefundingContext.php
  tests/Behat/Context/Ui/RefundingContext.php
  tests/Behat/Page/Admin/OrderRefundsPage.php
  tests/Behat/Page/Admin/OrderRefundsPageInterface.php
  tests/Behat/Resources/services.xml
Labels: feature
