Repository Sylius/RefundPlugin, pull requests merged in 2018-10, with the labels that each got.

#87 Describe installation instructions with SymfonyFlex
  README.md
  docs/legacy_installation.md
Labels: Maintenance

#84 Change partial refunds inputs UI + fix UI validation
  src/Resources/views/orderRefunds.html.twig
Labels: UI, bug

#85 RefundPayment - Payment relation
  spec/Event/RefundPaymentGeneratedSpec.php
  spec/ProcessManager/RefundPaymentProcessManagerSpec.php
  spec/Provider/DefaultRelatedPaymentIdProviderSpec.php
  src/Event/RefundPaymentGenerated.php
  src/Exception/CompletedPaymentNotFound.php
  src/ProcessManager/RefundPaymentProcessManager.php
  src/Provider/DefaultRelatedPaymentIdProvider.php
  src/Provider/RelatedPaymentIdProviderInterface.php
  src/Resources/config/services/event_bus.xml
  src/Resources/config/services/provider.xml
Labels: enhancement

#86 Support only for offline payment methods
  composer.json
  features/refunding_single_order_unit.feature
  phpstan.neon
  spec/Provider/OfflineRefundPaymentMethodsProviderSpec.php
  src/Action/Admin/OrderRefundsListAction.php
  src/Action/Admin/RefundUnitsAction.php
  src/Entity/CreditMemoUnit.php
  src/Provider/OfflineRefundPaymentMethodsProvider.php
  src/Provider/RefundPaymentMethodsProviderInterface.php
  src/Resources/config/services/actions.xml
  src/Resources/config/services/provider.xml
  tests/Behat/Context/Ui/RefundingContext.php
Labels: enhancement

#95 #78 Improve refund payment UI
  src/Resources/views/Order/Admin/RefundPayment/list.html.twig
  src/Resources/views/RefundPayment/Label/State/completed.html.twig
  src/Resources/views/RefundPayment/Label/State/new.html.twig
Labels: Hacktoberfest, UI, bug

#96 Hide unneeded "refund" button
  src/Resources/views/SyliusAdminBundle/Order/Show/_payment.html.twig
  tests/Application/templates/bundles/SyliusAdminBundle/Order/Show/_payment.html.twig
Labels: enhancement
