Repository Sylius/RefundPlugin, pull requests merged in 2018-11, with the labels that each got.

#97 Remove unnecessary config for Sylius Mailer
  src/Resources/config/app/config.yml
Labels: bug

#89 Switch to Symfony Messenger
  .travis.yml
  composer.json
  docs/legacy_installation.md
  spec/CommandHandler/GenerateCreditMemoHandlerSpec.php
  spec/CommandHandler/RefundUnitsHandlerSpec.php
  spec/Creator/RefundUnitsCommandCreatorSpec.php
  spec/ProcessManager/CreditMemoProcessManagerSpec.php
  spec/ProcessManager/RefundPaymentProcessManagerSpec.php
  spec/Refunder/OrderItemUnitsRefunderSpec.php
  spec/Refunder/OrderShipmentsRefunderSpec.php
  src/Action/Admin/RefundUnitsAction.php
  src/Command/GenerateCreditMemo.php
  src/Command/RefundUnits.php
  src/CommandHandler/GenerateCreditMemoHandler.php
  src/CommandHandler/RefundUnitsHandler.php
  src/Creator/CommandCreatorInterface.php
  src/Creator/RefundUnitsCommandCreator.php
  src/Creator/RefundUnitsCommandCreatorInterface.php
  src/Event/UnitsRefunded.php
  src/ProcessManager/CreditMemoProcessManager.php
  src/ProcessManager/RefundPaymentProcessManager.php
  src/Refunder/OrderItemUnitsRefunder.php
  src/Refunder/OrderShipmentsRefunder.php
  src/Resources/config/app/config.yml
  src/Resources/config/services.xml
  src/Resources/config/services/actions.xml
  src/Resources/config/services/command_bus.xml
  src/Resources/config/services/event_bus.xml
  tests/Application/config/bundles.php
  tests/Application/config/packages/test/sylius_refund.yaml
  tests/Behat/Context/Application/RefundingContext.php
  tests/Behat/Context/Setup/RefundingContext.php
  tests/Behat/Resources/services.xml
Labels: Maintenance, enhancement

#102 Use services from FoB/PageObjectExtension
  tests/Behat/Context/Ui/RefundingContext.php
  tests/Behat/Page/Admin/CreditMemoDetailsPage.php
  tests/Behat/Page/Admin/CreditMemoDetailsPageInterface.php
  tests/Behat/Page/Admin/OrderRefundsPage.php
  tests/Behat/Page/Admin/OrderRefundsPageInterface.php
  tests/Behat/Page/Shop/Order/ShowPage.php
Labels: Maintenance, bug

#101 Pre-select original payment method for refund payment
  features/preselecting_refund_payment_method_based_on_order.feature
  src/Resources/translations/messages.en.yml
  src/Resources/views/orderRefunds.html.twig
  tests/Behat/Context/Ui/RefundingContext.php
  tests/Behat/Page/Admin/OrderRefundsPage.php
Labels: feature
