Repository Sylius/RefundPlugin, pull requests merged in 2019-05, with the labels that each got.

#133 Symfony-extension version temporarily locked
  composer.json
Labels: Bug

#131 Check events dispatching for real
  spec/CommandHandler/GenerateCreditMemoHandlerSpec.php
  spec/CommandHandler/RefundUnitsHandlerSpec.php
  spec/ProcessManager/CreditMemoProcessManagerSpec.php
  spec/ProcessManager/RefundPaymentProcessManagerSpec.php
  spec/Refunder/OrderItemUnitsRefunderSpec.php
  spec/Refunder/OrderShipmentsRefunderSpec.php
Labels: Bug

#136 [Doctrine] Added php-enum library and upgrade doctrine mapping with custom type
  composer.json
  migrations/Version20190517064223.php
  spec/Model/RefundTypeSpec.php
  src/Entity/Refund.php
  src/Entity/Type/RefundEnumType.php
  src/Model/RefundType.php
  src/Provider/RemainingTotalProvider.php
  src/Provider/UnitRefundedTotalProvider.php
  src/Resources/config/app/config.yml
  src/Resources/config/doctrine/Refund.orm.xml
  tests/Behat/Context/Application/RefundingContext.php
Labels: Enhancement

#140 Improve refund UX
  src/Resources/translations/messages.en.yml
  src/Resources/views/orderRefunds.html.twig
  src/Twig/OrderRefundsExtension.php
  tests/Behat/Page/Admin/OrderRefundsPage.php
Labels: Enhancement, UX/UI
