Repository Sylius/RefundPlugin, pull requests merged in 2019-10, with the labels that each got.

#155 Remove embedded to oneToOne, add new Migrations
  UPGRADE.md
  migrations/Version20190928200659.php
  spec/Entity/CreditMemoChannelSpec.php
  spec/Entity/CreditMemoSpec.php
  spec/Entity/CustomerBillingDataSpec.php
  spec/Entity/ShopBillingDataSpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  src/Entity/CreditMemo.php
  src/Entity/CreditMemoChannel.php
  src/Entity/CreditMemoInterface.php
  src/Entity/CustomerBillingData.php
  src/Entity/CustomerBillingDataInterface.php
  src/Entity/ShopBillingData.php
  src/Entity/ShopBillingDataInterface.php
  src/Generator/CreditMemoGenerator.php
  src/Resources/config/doctrine/CreditMemo.orm.xml
  src/Resources/config/doctrine/CreditMemoChannel.orm.xml
  src/Resources/config/doctrine/CreditMemoSequence.orm.xml
  src/Resources/config/doctrine/CustomerBillingData.orm.xml
  src/Resources/config/doctrine/Refund.orm.xml
  src/Resources/config/doctrine/RefundPayment.orm.xml
  src/Resources/config/doctrine/ShopBillingData.orm.xml
  tests/Application/src/Migrations/Version20190508083953.php
  tests/Application/src/Migrations/Version20190607135638.php
  tests/Behat/Context/Application/CreditMemoContext.php
  tests/Behat/Context/Setup/ChannelContext.php
  tests/Behat/Context/Ui/CreditMemoContext.php
Labels: Enhancement

#153 Fix refund calculator conversion
  features/refunding_order_units.feature
  src/Calculator/UnitRefundTotalCalculator.php
  tests/Behat/Context/Ui/RefundingContext.php
Labels: Bug

#160 Require stable version of ResourceBundle
  composer.json
Labels: Enhancement

#163 Make entity properties protected
  src/Entity/CreditMemo.php
  src/Entity/CreditMemoSequence.php
  src/Entity/CreditMemoUnit.php
  src/Entity/CustomerBillingData.php
  src/Entity/Refund.php
  src/Entity/RefundPayment.php
  src/Entity/ShopBillingData.php
Labels: Enhancement, Maintenance
