Repository Sylius/RefundPlugin, pull requests merged in 2020-04, with the labels that each got.

#200 Misc refactor
  migrations/Version20200306145439.php
  migrations/Version20200306153205.php
  migrations/Version20200310094633.php
  migrations/Version20200310185620.php
  spec/Command/GenerateCreditMemoSpec.php
  spec/Converter/ShipmentLineItemsConverterSpec.php
  spec/Entity/CreditMemoSequenceSpec.php
  spec/Entity/CreditMemoSpec.php
  spec/Entity/CustomerBillingDataSpec.php
  spec/Factory/CreditMemoSequenceFactorySpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  spec/Generator/SequentialNumberGeneratorSpec.php
  spec/ProcessManager/RefundPaymentProcessManagerSpec.php
  spec/Provider/CurrentDateTimeImmutableProviderSpec.php
  spec/Provider/CurrentDateTimeProviderSpec.php
  src/Command/GenerateCreditMemo.php
  src/Command/RefundUnits.php
  src/Converter/LineItemsConverter.php
  src/Converter/ShipmentLineItemsConverter.php
  src/Entity/CreditMemo.php
  src/Entity/CreditMemoInterface.php
  src/Entity/CreditMemoSequence.php
  src/Entity/CreditMemoSequenceInterface.php
  src/Entity/CustomerBillingData.php
  src/Entity/CustomerBillingDataInterface.php
  src/Event/UnitsRefunded.php
  src/Factory/CreditMemoSequenceFactory.php
  src/Factory/CreditMemoSequenceFactoryInterface.php
  src/Factory/SequenceFactoryInterface.php
  src/Generator/CreditMemoGenerator.php
  src/Generator/SequentialNumberGenerator.php
  src/Provider/CurrentDateTimeImmutableProvider.php
  src/Provider/CurrentDateTimeImmutableProviderInterface.php
  src/Provider/CurrentDateTimeProvider.php
  src/Provider/CurrentDateTimeProviderInterface.php
  src/Resources/config/doctrine/CreditMemo.orm.xml
  src/Resources/config/doctrine/CustomerBillingData.orm.xml
  src/Resources/config/doctrine/RefundPayment.orm.xml
  src/Resources/config/services/generator.xml
  src/Resources/config/services/provider.xml
  src/Resources/views/Download/creditMemo.html.twig
  src/Resources/views/Order/Admin/CreditMemo/details.html.twig
  src/Validator/RefundAmountValidator.php
  tests/Behat/Context/Application/CreditMemoContext.php
  tests/Behat/Context/Ui/CreditMemoContext.php
  tests/Behat/Resources/services.xml
Labels: Bug, Enhancement

#202 [DB] Remove `COMMENT` database configuration
  src/Entity/Type/RefundEnumType.php
Labels: DX, Enhancement

#206 [Doc] Update UPGRADE file
  UPGRADE.md
Labels: Maintenance
