Repository Sylius/RefundPlugin, pull requests merged in 2020-01, with the labels that each got.

#172 Navigation via breadcrumbs between credit memo - Order and refund page - order
  features/browsing_list_of_all_credit_memos.feature
  migrations/Version20191230121402.php
  spec/Checker/CreditMemoCustomerRelationCheckerSpec.php
  spec/CommandHandler/GenerateCreditMemoHandlerSpec.php
  spec/Entity/CreditMemoSpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  src/Checker/CreditMemoCustomerRelationChecker.php
  src/CommandHandler/GenerateCreditMemoHandler.php
  src/CommandHandler/SendCreditMemoHandler.php
  src/Entity/CreditMemo.php
  src/Entity/CreditMemoInterface.php
  src/Generator/CreditMemoGenerator.php
  src/Generator/CreditMemoGeneratorInterface.php
  src/Resources/config/admin_routing.yml
  src/Resources/config/app/config.yml
  src/Resources/config/doctrine/CreditMemo.orm.xml
  src/Resources/config/services.xml
  src/Resources/config/services/command_bus.xml
  src/Resources/config/shop_routing.yml
  src/Resources/views/Order/Admin/CreditMemo/_breadcrumb.html.twig
  src/Resources/views/Order/Admin/CreditMemo/_header.html.twig
  src/Resources/views/Order/Admin/CreditMemo/details.html.twig
  src/Resources/views/Order/Admin/CreditMemo/list.html.twig
  src/Resources/views/Order/Admin/creditMemos.html.twig
  src/Resources/views/Order/Grid/Field/number.html.twig
  src/Resources/views/Order/Shop/creditMemos.html.twig
  src/Resources/views/_breadcrumb.html.twig
  src/Resources/views/orderRefunds.html.twig
  src/Ui/RedirectToOrderShowAction.php
  tests/Behat/Context/Application/CreditMemoContext.php
  tests/Behat/Context/Transform/OrderContext.php
  tests/Behat/Context/Ui/CreditMemoContext.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites.yml
Labels: Enhancement

#174 [CreditMemo] Remove unused service from credit memo generator
  spec/Generator/CreditMemoGeneratorSpec.php
  src/Generator/CreditMemoGenerator.php
  src/Resources/config/services/generator.xml
Labels: DX, Maintenance

#173 [CreditMemo] Add tax items to credit memo
  features/having_credit_memo_generated.feature
  migrations/Version20200113091731.php
  spec/Entity/CreditMemoSpec.php
  spec/Entity/TaxItemSpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  spec/Generator/TaxItemsGeneratorSpec.php
  src/Entity/CreditMemo.php
  src/Entity/CreditMemoInterface.php
  src/Entity/TaxItem.php
  src/Entity/TaxItemInterface.php
  src/Generator/CreditMemoGenerator.php
  src/Generator/TaxItemsGenerator.php
  src/Generator/TaxItemsGeneratorInterface.php
  src/Resources/config/doctrine/CreditMemo.orm.xml
  src/Resources/config/services/generator.xml
  src/Resources/views/Download/creditMemo.html.twig
  src/Resources/views/Order/Admin/CreditMemo/details.html.twig
  tests/Behat/Context/Application/CreditMemoContext.php
  tests/Behat/Context/Ui/CreditMemoContext.php
  tests/Behat/Page/Admin/CreditMemoDetailsPage.php
  tests/Behat/Page/Admin/CreditMemoDetailsPageInterface.php
Labels: Feature

#175 Configuring supported gateways instead of hardcoding them
  UPGRADE.md
  spec/Provider/SupportedRefundPaymentMethodsProviderSpec.php
  src/Provider/SupportedRefundPaymentMethodsProvider.php
  src/Resources/config/services/provider.xml
Labels: DX, Enhancement

#176 Add changelogs to v0.10.1 and v1.0.0-RC.1
  CHANGELOG.md
  UPGRADE.md
Labels: Maintenance

#177 Update README with refunds payment information
  README.md
Labels: Enhancement, Maintenance

#179 [CreditMemo] Rework credit memo
  UPGRADE.md
  features/having_credit_memo_generated.feature
  features/having_order_partially_refunded.feature
  features/providing_comment_for_credit_memo.feature
  features/refunding_part_of_order_unit.feature
  features/refunding_part_of_shipment.feature
  features/viewing_details_of_credit_memo.feature
  features/viewing_details_of_credit_memo_with_promotion_applied.feature
  migrations/Version20200125182414.php
  spec/Converter/LineItemsConverterSpec.php
  spec/Converter/ShipmentLineItemsConverterSpec.php
  spec/Entity/CreditMemoSpec.php
  spec/Entity/CreditMemoUnitSpec.php
  spec/Entity/LineItemSpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  spec/Generator/OrderItemUnitCreditMemoUnitGeneratorSpec.php
  spec/Generator/TaxItemsGeneratorSpec.php
  src/Converter/LineItemsConverter.php
  src/Converter/LineItemsConverterInterface.php
  src/Converter/ShipmentLineItemsConverter.php
  src/Entity/CreditMemo.php
  src/Entity/CreditMemoInterface.php
  src/Entity/CreditMemoUnit.php
  src/Entity/CreditMemoUnitInterface.php
  src/Entity/LineItem.php
  src/Entity/LineItemInterface.php
  src/Exception/LineItemsCannotBeMerged.php
  src/Generator/CreditMemoGenerator.php
  src/Generator/CreditMemoUnitGeneratorInterface.php
  src/Generator/OrderItemUnitCreditMemoUnitGenerator.php
  src/Generator/ShipmentCreditMemoUnitGenerator.php
  src/Generator/TaxItemsGenerator.php
  src/Generator/TaxItemsGeneratorInterface.php
  src/Resources/config/app/config.yml
  src/Resources/config/doctrine/CreditMemo.orm.xml
  src/Resources/config/doctrine/LineItem.orm.xml
  src/Resources/config/services.xml
  src/Resources/config/services/converter.xml
  src/Resources/config/services/generator.xml
  src/Resources/translations/messages.en.yml
  src/Resources/views/Download/creditMemo.html.twig
  src/Resources/views/Order/Admin/CreditMemo/details.html.twig
  tests/Behat/Context/Application/CreditMemoContext.php
  tests/Behat/Context/Setup/RefundingContext.php
  tests/Behat/Context/Transform/PriceContext.php
  tests/Behat/Context/Ui/CreditMemoContext.php
  tests/Behat/Page/Admin/CreditMemoDetailsPage.php
  tests/Behat/Page/Admin/CreditMemoDetailsPageInterface.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites.yml
Labels: Enhancement

#182 [TaxItem] Make tax item a resource
  UPGRADE.md
  migrations/Version20200131082149.php
  spec/Entity/CreditMemoSpec.php
  spec/Entity/TaxItemSpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  src/Entity/CreditMemo.php
  src/Entity/CreditMemoInterface.php
  src/Entity/TaxItem.php
  src/Entity/TaxItemInterface.php
  src/Generator/CreditMemoGenerator.php
  src/Resources/config/app/config.yml
  src/Resources/config/doctrine/CreditMemo.orm.xml
  src/Resources/config/doctrine/TaxItem.orm.xml
  tests/Behat/Context/Application/CreditMemoContext.php
Labels: DX, Enhancement

#181 Extract tax rate provider from line items converter
  spec/Converter/LineItemsConverterSpec.php
  spec/Provider/LabelBasedTaxRateProviderSpec.php
  src/Converter/LineItemsConverter.php
  src/Provider/LabelBasedTaxRateProvider.php
  src/Provider/TaxRateProviderInterface.php
  src/Resources/config/services/converter.xml
  src/Resources/config/services/provider.xml
Labels: DX, Enhancement

#180 [Refunds] Disable refund when order is free
  features/being_unable_to_refund_free_order.feature
  features/refunding_single_order_unit.feature
  spec/Checker/OrderRefundingAvailabilityCheckerSpec.php
  spec/Checker/OrderRefundsListAvailabilityCheckerSpec.php
  src/Action/Admin/OrderRefundsListAction.php
  src/Checker/OrderRefundingAvailabilityChecker.php
  src/Checker/OrderRefundsListAvailabilityChecker.php
  src/Resources/translations/flashes.en.yml
  src/Resources/views/_paymentMethod.html.twig
  tests/Behat/Context/Setup/ProductContext.php
  tests/Behat/Context/Ui/ManagingOrdersContext.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites.yml
Labels: Enhancement

#183 Code standards fixes
  src/Checker/OrderRefundingAvailabilityChecker.php
  src/Checker/OrderRefundsListAvailabilityChecker.php
Labels: DX, Enhancement

#184 Merge pull request #184 from Zales0123/1.0.0-RC.2-changelog
  CHANGELOG.md
Labels: Maintenance
