Repository Sylius/RefundPlugin, pull requests merged in 2021-06, with the labels that each got.

#300 Use explicit bus in handlers configurations
  src/Resources/config/services/command_bus.xml
Labels: Maintenance

#299 Refactor credit memo number generator
  UPGRADE.md
  spec/Factory/CreditMemoFactorySpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  spec/Generator/SequentialCreditMemoNumberGeneratorSpec.php
  src/Factory/CreditMemoFactory.php
  src/Generator/CreditMemoNumberGeneratorInterface.php
  src/Generator/NumberGeneratorInterface.php
  src/Generator/SequentialCreditMemoNumberGenerator.php
  src/Resources/config/services/factory.xml
  src/Resources/config/services/generator.xml
Labels: DX, Enhancement

#302 Use interfaces instead of FQCN as services ids + minor files refactor
  src/Resources/config/services.xml
  src/Resources/config/services/actions.xml
  src/Resources/config/services/checkers.xml
  src/Resources/config/services/command_bus.xml
  src/Resources/config/services/converters.xml
  src/Resources/config/services/creators.xml
  src/Resources/config/services/event_bus.xml
  src/Resources/config/services/factories.xml
  src/Resources/config/services/factory.xml
  src/Resources/config/services/generator.xml
  src/Resources/config/services/generators.xml
  src/Resources/config/services/listeners.xml
  src/Resources/config/services/provider.xml
  src/Resources/config/services/providers.xml
  src/Resources/config/services/state_resolvers.xml
  src/Resources/config/services/validator.xml
  src/Resources/config/services/validators.xml
  tests/Application/config/services_test.yaml
  tests/Behat/Resources/services.xml
Labels: DX, Maintenance

#304 Remove unneeded exclude from GitHub Actions
  .github/workflows/build.yml
Labels: Maintenance

#306 Change order number to Order relation on Refund
  UPGRADE.md
  spec/Checker/OrderFullyRefundedTotalCheckerSpec.php
  spec/Creator/RefundCreatorSpec.php
  spec/Entity/RefundSpec.php
  spec/Factory/RefundFactorySpec.php
  spec/Provider/OrderRefundedTotalProviderSpec.php
  src/Checker/OrderFullyRefundedTotalChecker.php
  src/Creator/RefundCreator.php
  src/Entity/Refund.php
  src/Entity/RefundInterface.php
  src/Factory/RefundFactory.php
  src/Factory/RefundFactoryInterface.php
  src/Migrations/Version20210608074013.php
  src/Provider/OrderRefundedTotalProvider.php
  src/Provider/OrderRefundedTotalProviderInterface.php
  src/Resources/config/doctrine/Refund.orm.xml
  src/Resources/config/services.xml
  src/Resources/config/services/creators.xml
  src/Twig/OrderRefundsExtension.php
  tests/Behat/Context/Application/RefundingContext.php
Labels: DX, Enhancement

#307 [RefundPayment] Change order number to Order relation on RefundPayment
  UPGRADE.md
  spec/Entity/RefundPaymentSpec.php
  spec/Factory/RefundPaymentFactorySpec.php
  spec/ProcessManager/RefundPaymentProcessManagerSpec.php
  spec/Provider/DefaultRelatedPaymentIdProviderSpec.php
  src/Doctrine/ORM/RefundPaymentRepository.php
  src/Entity/RefundPayment.php
  src/Entity/RefundPaymentInterface.php
  src/Factory/RefundPaymentFactory.php
  src/Factory/RefundPaymentFactoryInterface.php
  src/Migrations/Version20210609071246.php
  src/ProcessManager/RefundPaymentProcessManager.php
  src/Provider/DefaultRelatedPaymentIdProvider.php
  src/Repository/RefundPaymentRepositoryInterface.php
  src/Resources/config/app/config.yml
  src/Resources/config/doctrine/RefundPayment.orm.xml
  src/Resources/config/services/event_bus.xml
  src/Resources/config/services/providers.xml
  src/Resources/views/Order/Admin/RefundPayment/list.html.twig
  tests/Behat/Services/Factory/FailedRefundPaymentFactory.php
Labels: DX, Enhancement

#309 Order refund admin show rebuild
  src/Doctrine/ORM/RefundPaymentRepository.php
  src/Repository/RefundPaymentRepositoryInterface.php
  src/Resources/config/admin_routing.yml
  src/Resources/config/app/config.yml
  src/Resources/config/services.xml
  src/Resources/config/services/listeners.xml
  src/Resources/views/Order/Admin/RefundPayment/list.html.twig
  src/Resources/views/Order/Admin/_refundPayments.html.twig
  src/Resources/views/Order/Admin/refundPayments.html.twig
  src/Resources/views/SyliusAdminBundle/Order/Show/_payments.html.twig
  src/Twig/OrderRefundsExtension.php
  tests/Application/templates/bundles/SyliusAdminBundle/Order/Show/_payments.html.twig
  tests/Behat/Page/Admin/Order/ShowPage.php
Labels: Enhancement, UX/UI

#310 Replace deprecated twig extension
  src/Twig/OrderRefundsExtension.php
Labels: Maintenance

#308 Logo as parameter
  src/Resources/config/services.xml
  src/Resources/config/services/generators.xml
Labels: Enhancement

#313 Change CustomerBillingData to resource and create via factory
  UPGRADE.md
  phpstan.neon
  spec/Entity/CustomerBillingDataSpec.php
  spec/Factory/CustomerBillingDataFactorySpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  src/Entity/CustomerBillingData.php
  src/Entity/CustomerBillingDataInterface.php
  src/Factory/CustomerBillingDataFactory.php
  src/Factory/CustomerBillingDataFactoryInterface.php
  src/Generator/CreditMemoGenerator.php
  src/Resources/config/app/config.yml
  src/Resources/config/services/factories.xml
  src/Resources/config/services/generators.xml
  tests/Behat/Context/Application/CreditMemoContext.php
Labels: DX

#314 Add backward compatibility for old refund buses
  src/Resources/config/app/config.yml
Labels: Bug

#317 Replace Sonata block events with Sylius template events
  UPGRADE.md
  src/Resources/config/app/config.yml
  src/Resources/config/services/listeners.xml
  src/Resources/views/Order/Admin/creditMemos.html.twig
  src/Resources/views/Order/Shop/creditMemos.html.twig
Labels: Enhancement

#316 fix original payment method of refund
  features/seeing_original_payment_method_from_completed_payment_on_refund_page.feature
  src/Resources/views/_paymentMethod.html.twig
  tests/Behat/Context/Setup/PaymentContext.php
  tests/Behat/Context/Ui/RefundingContext.php
  tests/Behat/Page/Admin/OrderRefundsPage.php
  tests/Behat/Page/Admin/OrderRefundsPageInterface.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites.yml
Labels: Bug

#318 Fix plugin versions in UPGRADE file
  UPGRADE.md
Labels: Maintenance

#315 Shop billing data as resource
  UPGRADE.md
  spec/Entity/ShopBillingDataSpec.php
  spec/Factory/ShopBillingDataFactorySpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  src/Entity/ShopBillingData.php
  src/Entity/ShopBillingDataInterface.php
  src/Factory/ShopBillingDataFactory.php
  src/Factory/ShopBillingDataFactoryInterface.php
  src/Generator/CreditMemoGenerator.php
  src/Resources/config/app/config.yml
  src/Resources/config/services/factories.xml
  src/Resources/config/services/generators.xml
  tests/Behat/Context/Application/CreditMemoContext.php
Labels: Enhancement

#312 Improve dx with extending refund type
  src/Command/GenerateCreditMemo.php
  src/Command/RefundUnits.php
  src/Command/SendCreditMemo.php
  src/Event/CreditMemoGenerated.php
  src/Event/RefundPaymentGenerated.php
  src/Event/ShipmentRefunded.php
  src/Event/UnitRefunded.php
  src/Event/UnitsRefunded.php
Labels: DX

#320 [RefundPayment] Make the Refund customization easier
  UPGRADE.md
  features/seeing_credit_memos_on_admin_order_view.feature
  spec/Converter/RefundUnitsConverterSpec.php
  spec/Creator/RefundUnitsCommandCreatorSpec.php
  spec/Factory/RefundPaymentFactorySpec.php
  spec/ProcessManager/RefundPaymentProcessManagerSpec.php
  src/Converter/RefundUnitsConverter.php
  src/Converter/RefundUnitsConverterInterface.php
  src/Creator/RefundUnitsCommandCreator.php
  src/Factory/RefundPaymentFactory.php
  src/Factory/RefundPaymentFactoryInterface.php
  src/ProcessManager/RefundPaymentProcessManager.php
  src/Resources/config/app/config.yml
  src/Resources/config/services/converters.xml
  src/Resources/config/services/creators.xml
  src/Resources/config/services/event_bus.xml
  src/Resources/config/services/factories.xml
  tests/Application/config/services_test.yaml
  tests/Behat/Context/Setup/RefundingContext.php
  tests/Behat/Services/Factory/FailedRefundPaymentFactory.php
Labels: DX

#321 Minor improvements for RefundFactory and RefundPaymentFactory
  composer.json
  spec/Factory/RefundFactorySpec.php
  spec/Factory/RefundPaymentFactorySpec.php
  src/Factory/RefundFactory.php
  src/Factory/RefundPaymentFactory.php
  src/Factory/RefundPaymentFactoryInterface.php
  tests/Behat/Services/Factory/FailedRefundPaymentFactory.php
Labels: DX

#322 Change to a more meaningful message in factory exception
  src/Factory/RefundFactory.php
  src/Factory/RefundPaymentFactory.php
  tests/Behat/Services/Factory/FailedRefundPaymentFactory.php
Labels: DX
