Repository Sylius/RefundPlugin, pull requests merged in 2021-03, with the labels that each got.

#260 Fix OrderItemsTaxesApplicator with removed units
  spec/TaxesApplicator/OrderItemsTaxesApplicatorSpec.php
  src/TaxesApplicator/OrderItemsTaxesApplicator.php
Labels: Bug

#261 Update GitHub Actions to run on Sylius 1.9 instead of 1.9-beta
  .github/workflows/build.yml
  composer.json
Labels: Maintenance

#263 Check proper state during resolving order refunded state
  spec/StateResolver/OrderFullyRefundedStateResolverSpec.php
  src/StateResolver/OrderFullyRefundedStateResolver.php
Labels: Bug

#267 Update installation guides to install proper version of plugin
  README.md
  docs/legacy_installation.md
Labels: Maintenance

#268 update installation guides for sylius 1.8
  README.md
  docs/legacy_installation.md
Labels: Maintenance

#272 Add missing note about changes in constructor of ShipmentLineItemsConverter
  UPGRADE.md
Labels: Maintenance

#274 [CreditMemo] Add scenarios for viewing multiple shipments on credit memo
  features/viewing_details_of_credit_memo_with_multiple_shipments.feature
  tests/Behat/Context/Setup/RefundingContext.php
Labels: Enhancement
