Repository Sylius/RefundPlugin, pull requests merged in 2021-02, with the labels that each got.

#255 Refund shipping cost with promotion applied
  features/refunding_order_shipping_cost_with_promotion_applied.feature
  spec/PromotionAction/ShippingPercentageDiscountPromotionActionCommandSpec.php
  spec/TaxesApplicator/OrderShipmentTaxesApplicatorSpec.php
  src/PromotionAction/ShippingPercentageDiscountPromotionActionCommand.php
  src/Resources/config/services.xml
  src/Resources/views/_shipping.html.twig
  src/TaxesApplicator/OrderShipmentTaxesApplicator.php
  tests/Behat/Page/Admin/OrderRefundsPage.php
Labels: Bug

#254 Allow for Sylius 1.8 & 1.9 and Symfony 4.4 & 5.2
  .github/workflows/build.yml
  README.md
  composer.json
  docs/legacy_installation.md
  spec/CommandHandler/GenerateCreditMemoHandlerSpec.php
  spec/Creator/RefundCreatorSpec.php
  spec/Generator/CreditMemoPdfFileGeneratorSpec.php
  spec/Generator/SequentialNumberGeneratorSpec.php
  spec/StateResolver/OrderFullyRefundedStateResolverSpec.php
  spec/StateResolver/OrderPartiallyRefundedStateResolverSpec.php
  spec/StateResolver/RefundPaymentCompletedStateApplierSpec.php
  src/Action/CompleteRefundPaymentAction.php
  src/CommandHandler/GenerateCreditMemoHandler.php
  src/Creator/RefundCreator.php
  src/DependencyInjection/Configuration.php
  src/Generator/CreditMemoPdfFileGenerator.php
  src/Generator/SequentialNumberGenerator.php
  src/Migrations/Version20201130071338.php
  src/Migrations/Version20201204071301.php
  src/Resources/config/admin_routing.yml
  src/Resources/config/services/generator.xml
  src/Resources/views/Grid/Filter/channel.html.twig
  src/Resources/views/orderRefunds.html.twig
  src/StateResolver/OrderFullyRefundedStateResolver.php
  src/StateResolver/OrderPartiallyRefundedStateResolver.php
  src/StateResolver/RefundPaymentCompletedStateApplier.php
  tests/Application/.env
  tests/Application/Kernel.php
  tests/Application/config/bundles.php
  tests/Application/config/packages/_sylius.yaml
  tests/Application/config/packages/framework.yaml
  tests/Application/config/packages/sylius_refund.yaml
  tests/Application/config/packages/test/sylius_refund.yaml
  tests/Application/config/sylius/1.8/bundles.php
  tests/Application/config/sylius/1.8/packages/dev/jms_serializer.yaml
  tests/Application/config/sylius/1.8/packages/framework.yaml
  tests/Application/config/sylius/1.8/packages/jms_serializer.yaml
  tests/Application/config/sylius/1.8/packages/prod/jms_serializer.yaml
  tests/Application/config/sylius/1.8/routes/dev/twig.yaml
  tests/Application/config/sylius/1.9/bundles.php
  tests/Application/config/sylius/1.9/packages/dev/jms_serializer.yaml
  tests/Application/config/sylius/1.9/packages/jms_serializer.yaml
  tests/Application/config/sylius/1.9/packages/prod/jms_serializer.yaml
  tests/Application/public/index.php
  tests/Behat/Context/Application/CreditMemoContext.php
  tests/Behat/Context/Setup/ChannelContext.php
  tests/Behat/Context/Setup/OrderContext.php
  tests/Behat/Context/Ui/CreditMemoContext.php
  tests/Behat/Resources/services.xml
Labels: Maintenance

#257 [Adjustment] Update down methods of duplicated migrations not to execute if the changes already exist in db
  src/Migrations/Version20201130071338.php
  src/Migrations/Version20201204071301.php
Labels: DX, Maintenance
