Repository Sylius/RefundPlugin, pull requests merged in 2021-05, with the labels that each got.

#289 [CreditMemo] Replace unnecessary custom ChannelFilter with the Sylius entity filter
  UPGRADE.md
  features/filtering_credit_memos.feature
  spec/Grid/Filter/ChannelFilterSpec.php
  src/Form/Type/ChannelFilterType.php
  src/Grid/Filter/ChannelFilter.php
  src/Resources/config/app/config.yml
  src/Resources/config/services.xml
  src/Resources/views/Grid/Filter/channel.html.twig
  tests/Behat/Page/Admin/CreditMemoIndexPage.php
Labels: DX, Maintenance

#291 Remove support for Sylius 1.8
  .github/workflows/build.yml
  composer.json
  spec/Converter/ShipmentLineItemsConverterSpec.php
  spec/OrderProcessor/OrderTaxesProcessorSpec.php
  spec/OrderProcessor/ShippingChargesProcessorSpec.php
  spec/PromotionAction/ShippingPercentageDiscountPromotionActionCommandSpec.php
  spec/Provider/RemainingTotalProviderSpec.php
  spec/Provider/TaxRateProviderSpec.php
  spec/TaxesApplicator/OrderItemUnitsTaxesApplicatorSpec.php
  spec/TaxesApplicator/OrderItemsTaxesApplicatorSpec.php
  spec/TaxesApplicator/OrderShipmentTaxesApplicatorSpec.php
  src/Converter/ShipmentLineItemsConverter.php
  src/Entity/AdjustmentInterface.php
  src/Entity/AdjustmentTrait.php
  src/Entity/ShipmentInterface.php
  src/Entity/ShipmentTrait.php
  src/Migrations/Version20201130071338.php
  src/Migrations/Version20201204071301.php
  src/Migrations/Version20201208105207.php
  src/OrderProcessor/OrderTaxesProcessor.php
  src/OrderProcessor/ShippingChargesProcessor.php
  src/PromotionAction/ShippingPercentageDiscountPromotionActionCommand.php
  src/Provider/RemainingTotalProvider.php
  src/Provider/TaxRateProvider.php
  src/Resources/config/services.xml
  src/TaxesApplicator/OrderItemUnitsTaxesApplicator.php
  src/TaxesApplicator/OrderItemsTaxesApplicator.php
  src/TaxesApplicator/OrderShipmentTaxesApplicator.php
  tests/Application/Kernel.php
  tests/Application/config/bundles.php
  tests/Application/config/packages/_sylius.yaml
  tests/Application/config/packages/dev/jms_serializer.yaml
  tests/Application/config/packages/doctrine.yaml
  tests/Application/config/packages/jms_serializer.yaml
  tests/Application/config/packages/prod/jms_serializer.yaml
  tests/Application/config/sylius/1.8/bundles.php
  tests/Application/config/sylius/1.8/packages/dev/jms_serializer.yaml
  tests/Application/config/sylius/1.8/packages/framework.yaml
  tests/Application/config/sylius/1.8/packages/jms_serializer.yaml
  tests/Application/config/sylius/1.8/packages/prod/jms_serializer.yaml
  tests/Application/config/sylius/1.8/routes/dev/twig.yaml
  tests/Application/config/sylius/1.9/bundles.php
  tests/Application/src/Entity/Adjustment.php
  tests/Application/src/Entity/Shipment.php
  tests/Behat/Context/Setup/RefundingContext.php
Labels: Maintenance

#295 [CreditMemo] Refactor creating CreditMemo to use a factory
  UPGRADE.md
  spec/Entity/CreditMemoSpec.php
  spec/Factory/CreditMemoFactorySpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  src/Entity/CreditMemo.php
  src/Entity/CreditMemoInterface.php
  src/Factory/CreditMemoFactory.php
  src/Factory/CreditMemoFactoryInterface.php
  src/Generator/CreditMemoGenerator.php
  src/Resources/config/services.xml
  src/Resources/config/services/factory.xml
  src/Resources/config/services/generator.xml
Labels: DX

#296 Always create RefundPayment after CreditMemo
  README.md
  UPGRADE.md
  features/not_seeing_refund_payments_and_credit_memos_on_admin_order_view.feature
  spec/ProcessManager/CreditMemoProcessManagerSpec.php
  spec/ProcessManager/RefundPaymentProcessManagerSpec.php
  spec/ProcessManager/UnitsRefundedProcessManagerSpec.php
  src/ProcessManager/CreditMemoProcessManager.php
  src/ProcessManager/RefundPaymentProcessManager.php
  src/ProcessManager/UnitsRefundedProcessManager.php
  src/ProcessManager/UnitsRefundedProcessManagerInterface.php
  src/ProcessManager/UnitsRefundedProcessStepInterface.php
  src/Resources/config/services/event_bus.xml
  tests/Application/config/services_test.yaml
  tests/Behat/Context/Setup/RefundingContext.php
  tests/Behat/Context/Ui/ManagingOrdersContext.php
  tests/Behat/Page/Admin/Order/ShowPage.php
  tests/Behat/Page/Admin/Order/ShowPageInterface.php
  tests/Behat/Resources/services.xml
  tests/Behat/Services/Factory/FailedRefundPaymentFactory.php
  tests/Behat/Services/Generator/FailedCreditMemoGenerator.php
Labels: Bug, DX, Enhancement

#297 Add interface prefix to number generator
  UPGRADE.md
  spec/Factory/CreditMemoFactorySpec.php
  spec/Generator/CreditMemoGeneratorSpec.php
  spec/Generator/SequentialNumberGeneratorSpec.php
  src/Factory/CreditMemoFactory.php
  src/Generator/NumberGeneratorInterface.php
  src/Generator/SequentialNumberGenerator.php
Labels: DX

#301 Fix build for version 5.3.0 of symfony/http-foundation
  src/Creator/RefundUnitsCommandCreator.php
Labels: Bug, Maintenance
