Repository Sylius/RefundPlugin, pull requests merged in 2021-01, with the labels that each got.

#238 [Maintenance] Remove security checker config
  .github/workflows/build.yml
  tests/Application/config/packages/security_checker.yaml
Labels: Maintenance

#244 [Maintenance] Drop Sylius 1.7 support
  .github/workflows/build.yml
  composer.json
  etc/sylius17/bundles.php
  etc/sylius17/doctrine_migrations.yaml
  etc/sylius17/migrations/Version20170912085504.php
  etc/sylius17/migrations/Version20170913125128.php
  etc/sylius17/migrations/Version20171003103916.php
  etc/sylius17/migrations/Version20180102140039.php
  etc/sylius17/migrations/Version20190109095211.php
  etc/sylius17/migrations/Version20190109160409.php
  etc/sylius17/migrations/Version20190508083953.php
  etc/sylius17/migrations/Version20190607135638.php
  etc/sylius17/migrations/Version20200110132702.php
  etc/sylius17/migrations/Version20200122082429.php
  etc/sylius17/migrations/Version20200202104152.php
  etc/sylius17/security.yaml
  phpstan.neon
  src/DependencyInjection/SyliusRefundExtension.php
  tests/Application/.env
  tests/Application/config/packages/lexik_jwt_authentication.yaml
  tests/Application/config/packages/security.yaml
Labels: Maintenance

#245 Remove final tags from resource entities
  src/Entity/CreditMemo.php
  src/Entity/LineItem.php
  src/Entity/Refund.php
  src/Entity/RefundPayment.php
  src/Entity/TaxItem.php
Labels: DX

#242 Refunding shipments with taxes
  UPGRADE.md
  composer.json
  easy-coding-standard.yml
  features/refunding_order_shipping_cost.feature
  spec/Converter/ShipmentLineItemsConverterSpec.php
  spec/OrderProcessor/OrderTaxesProcessorSpec.php
  spec/OrderProcessor/ShippingChargesProcessorSpec.php
  spec/Provider/RemainingTotalProviderSpec.php
  spec/TaxesApplicator/OrderItemUnitsTaxesApplicatorSpec.php
  spec/TaxesApplicator/OrderItemsTaxesApplicatorSpec.php
  spec/TaxesApplicator/OrderShipmentTaxesApplicatorSpec.php
  src/Converter/ShipmentLineItemsConverter.php
  src/DependencyInjection/SyliusRefundExtension.php
  src/Entity/AdjustmentInterface.php
  src/Entity/AdjustmentTrait.php
  src/Entity/ShipmentInterface.php
  src/Entity/ShipmentTrait.php
  src/Migrations/Version20201130071338.php
  src/Migrations/Version20201204071301.php
  src/Migrations/Version20201208105207.php
  src/OrderProcessor/OrderTaxesProcessor.php
  src/OrderProcessor/ShippingChargesProcessor.php
  src/Provider/RemainingTotalProvider.php
  src/Resources/config/services.xml
  src/Resources/views/_shipping.html.twig
  src/TaxesApplicator/OrderItemUnitsTaxesApplicator.php
  src/TaxesApplicator/OrderItemsTaxesApplicator.php
  src/TaxesApplicator/OrderShipmentTaxesApplicator.php
  tests/Application/config/packages/_sylius.yaml
  tests/Application/config/packages/doctrine.yaml
  tests/Application/src/Entity/Adjustment.php
  tests/Application/src/Entity/Shipment.php
Labels: Bug

#248 [Shipment] Improve interface inheritance
  src/Converter/ShipmentLineItemsConverter.php
  src/Entity/AdjustmentInterface.php
  src/Entity/AdjustmentTrait.php
  src/Entity/ShipmentInterface.php
  src/Provider/RemainingTotalProvider.php
Labels: Bug, DX, Maintenance
