Repository Sylius/RefundPlugin, pull requests merged in 2022-03, with the labels that each got.

#350 [Maintenance] Add information about supported branches
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: Maintenance

#354 [Maintenance] Fix header of information about supported branches
  README.md
Labels: Maintenance

#358 [Maintenance] Bump up Sylius versions to fix the build
  .github/workflows/build.yml
  composer.json
Labels: Bug, Maintenance

#355 [GitHub Actions] Configure workflow to run on the workflow_dispatch event
  .github/workflows/build.yml
Labels: Maintenance

#359 [Credit Memo] Sorting credit memos by order numbers
  features/sorting_credit_memos_by_order_number.feature
  src/Resources/config/app/config.yml
  tests/Behat/Context/Ui/CreditMemoContext.php
Labels: Bug

#361 Enable local file access in CreditMemoPdfFileGenerator
  UPGRADE-1.1.md
  spec/Generator/CreditMemoPdfFileGeneratorSpec.php
  spec/Generator/PdfOptionsGeneratorSpec.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SyliusRefundExtension.php
  src/Generator/CreditMemoPdfFileGenerator.php
  src/Generator/PdfOptionsGenerator.php
  src/Generator/PdfOptionsGeneratorInterface.php
  src/Resources/config/app/config.yml
  src/Resources/config/services/generators.xml
  tests/DependencyInjection/SyliusRefundConfigurationTest.php
Labels: Bug
