Repository Sylius/RefundPlugin, pull requests merged in 2022-11, with the labels that each got.

#385 [Maintenance] Add support for Sylius 1.12 with Symfony 5.4
  .github/workflows/build.yml
  composer.json
  tests/Application/.babelrc
  tests/Application/.env
  tests/Application/.gitignore
  tests/Application/Kernel.php
  tests/Application/assets/admin/entry.js
  tests/Application/assets/shop/entry.js
  tests/Application/config/bundles.php
  tests/Application/config/packages/assets.yaml
  tests/Application/config/packages/staging/swiftmailer.yaml
  tests/Application/config/packages/test_cached/swiftmailer.yaml
  tests/Application/config/packages/webpack_encore.yaml
  tests/Application/config/sylius/1.11/packages/dev/swiftmailer.yaml
  tests/Application/config/sylius/1.11/packages/staging/swiftmailer.yaml
  tests/Application/config/sylius/1.11/packages/swiftmailer.yaml
  tests/Application/config/sylius/1.11/packages/test/swiftmailer.yaml
  tests/Application/config/sylius/1.11/packages/test_cached/swiftmailer.yaml
  tests/Application/config/sylius/1.12/packages/mailer.yaml
  tests/Application/config/sylius/1.12/packages/test/mailer.yaml
  tests/Application/config/sylius/1.12/packages/test_cached/mailer.yaml
  tests/Application/gulpfile.babel.js
  tests/Application/package.json
  tests/Application/templates/bundles/SyliusAdminBundle/Security/_content.html.twig
  tests/Application/templates/bundles/SyliusAdminBundle/_scripts.html.twig
  tests/Application/templates/bundles/SyliusAdminBundle/_styles.html.twig
  tests/Application/templates/bundles/SyliusShopBundle/Layout/Header/_logo.html.twig
  tests/Application/templates/bundles/SyliusShopBundle/_scripts.html.twig
  tests/Application/templates/bundles/SyliusShopBundle/_styles.html.twig
  tests/Application/webpack.config.js
  tests/Behat/Context/Application/EmailsContext.php
  tests/Behat/Context/Application/RefundingContext.php
  tests/Behat/Context/Ui/RefundingContext.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/services/mailer.php
  tests/Behat/Resources/suites/ui/refunds.yaml
  tests/Behat/Services/Provider/MessagesProvider.php
Labels: Maintenance

#386 Add Symfony 6 support
  .github/workflows/build.yml
  composer.json
  phpstan.neon
  src/Action/Admin/OrderRefundsListAction.php
  src/Action/Admin/RefundUnitsAction.php
  src/Action/Admin/SendCreditMemoAction.php
  src/Action/CompleteRefundPaymentAction.php
  src/Converter/RefundUnitsConverter.php
  src/Factory/RefundFactory.php
  src/Factory/RefundPaymentFactory.php
  src/Factory/RefundTypeFactory.php
  src/Resources/config/admin_routing.yml
  src/Resources/config/services.xml
  src/Resources/config/services/actions.xml
  src/Resources/config/services/checkers.xml
  src/Resources/config/services/creators.xml
  src/Resources/config/services/factories.xml
  src/Resources/config/services/generators.xml
  src/Resources/config/services/providers.xml
  src/Resources/config/services/state_resolvers.xml
  src/Resources/config/services/validators.xml
  src/Resources/config/shop_routing.yml
  tests/Application/Kernel.php
  tests/Application/config/packages/security.yaml
  tests/Application/config/packages/test/framework.yaml
  tests/Application/config/packages/test_cached/framework.yaml
  tests/Application/config/routes/sylius_shop.yaml
  tests/Application/package.json
Labels: Feature, Maintenance, Dependencies

#391 Add missing csrf_token field
  src/Action/Admin/RefundUnitsAction.php
  src/Resources/config/services/actions.xml
  src/Resources/views/orderRefunds.html.twig
Labels: Bug

#388 [Templates] Adjust to the new Sylius shop UI styles
  src/Resources/views/Order/Shop/_creditMemos.html.twig
Labels: UX/UI

#393 [Maintenance] Update README and PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
  README.md
Labels: Maintenance
