Repository Sylius/RefundPlugin, pull requests merged in 2022-04, with the labels that each got.

#363 Use mapped superclasses for entities
  src/Resources/config/doctrine/CreditMemo.orm.xml
  src/Resources/config/doctrine/CustomerBillingData.orm.xml
  src/Resources/config/doctrine/ShopBillingData.orm.xml
Labels: DX

#362 [Maintenance] Add TwigToPdfGenerator
  spec/Generator/CreditMemoPdfFileGeneratorSpec.php
  spec/Generator/TwigToPdfGeneratorSpec.php
  src/Generator/CreditMemoPdfFileGenerator.php
  src/Generator/TwigToPdfGenerator.php
  src/Generator/TwigToPdfGeneratorInterface.php
  src/Resources/config/services/generators.xml
Labels: Maintenance, DX

#366 [Templates] Remove redundant template overriding
  tests/Application/templates/bundles/SyliusAdminBundle/Order/Label/State/fully_refunded.html.twig
Labels: Maintenance

#365 [Templates][Admin] Replace templates overriding with events
  README.md
  UPGRADE-1.2.md
  composer.json
  src/Resources/config/app/config.yml
  src/Resources/views/SyliusAdminBundle/Order/Show/_payment.html.twig
  src/Resources/views/SyliusAdminBundle/Order/Show/_payments.html.twig
  tests/Application/templates/bundles/SyliusAdminBundle/Order/Show/_payment.html.twig
  tests/Application/templates/bundles/SyliusAdminBundle/Order/Show/_payments.html.twig
Labels: Enhancement, DX

#368 Update supported branches in README file
  .github/workflows/build.yml
  README.md
Labels: Maintenance

#367 [Maintenance] Optional pdf generator
  .github/workflows/build.yml
  README.md
  behat.yml.dist
  composer.json
  features/pdf_generation_disabled/being_unable_to_download_credit_memo_as_pdf_file.feature
  features/pdf_generation_disabled/being_unable_to_download_credit_memo_on_customer_order_view.feature
  features/pdf_generation_enabled/downloading_credit_memo_as_pdf_file.feature
  features/pdf_generation_enabled/downloading_credit_memo_on_customer_order_view.feature
  spec/Sender/CreditMemoEmailSenderSpec.php
  src/Action/Admin/DownloadCreditMemoAction.php
  src/Action/Shop/DownloadCreditMemoAction.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SyliusRefundExtension.php
  src/Resources/config/app/config.yml
  src/Resources/config/services.xml
  src/Resources/config/services/actions.xml
  src/Resources/views/Order/Admin/CreditMemo/_detailsButton.html.twig
  src/Resources/views/Order/Admin/CreditMemo/_downloadButton.html.twig
  src/Resources/views/Order/Admin/CreditMemo/details.html.twig
  src/Resources/views/Order/Admin/CreditMemo/list.html.twig
  src/Resources/views/Order/Shop/_creditMemos.html.twig
  src/Resources/views/Order/Shop/_downloadButton.html.twig
  src/ResponseBuilder/CreditMemoFileResponseBuilder.php
  src/Sender/CreditMemoEmailSender.php
  tests/Application/Kernel.php
  tests/Application/etc/sylius_refund_pdf_generation_disabled.yaml
  tests/Application/tests/sylius_refund_disabled_pdf_generator.yaml
  tests/Behat/Context/Ui/CreditMemoContext.php
  tests/Behat/Context/Ui/Shop/Customer/CreditMemoContext.php
  tests/Behat/Page/Admin/CreditMemoDetailsPage.php
  tests/Behat/Page/Admin/CreditMemoDetailsPageInterface.php
  tests/Behat/Page/Admin/CreditMemoIndexPage.php
  tests/Behat/Page/Admin/CreditMemoIndexPageInterface.php
  tests/Behat/Page/Admin/Order/ShowPage.php
  tests/Behat/Page/Admin/Order/ShowPageInterface.php
  tests/Behat/Page/Shop/Order/ShowPage.php
  tests/Behat/Page/Shop/Order/ShowPageInterface.php
  tests/DependencyInjection/SyliusRefundConfigurationTest.php
  tests/DependencyInjection/SyliusRefundExtensionTest.php
Labels: Enhancement, Feature, Maintenance

#370 [GitHub Actions] Include build with PDF generation disabled to the main workflow
  .github/workflows/build.yml
Labels: Maintenance

#371 [Maintenance] Update README and PR template
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: Maintenance
