Repository Sylius/RefundPlugin, pull requests merged in 2023-06, with the labels that each got.

#412 [Composer] Require php-http/message-factory package
  .github/workflows/build.yml
  composer.json
Labels: Bug, Dependencies

#214 [DX] Easier tests for RefundUnits message
  src/Command/RefundUnits.php
Labels: DX

#413 Adjust supported versions in README file
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG-1.3.md
  README.md
Labels: Maintenance

#414 [RefundUnitsConverter] Change interface method signature
  src/Converter/RefundUnitsConverterInterface.php
  src/Creator/RefundUnitsCommandCreator.php
Labels: Bug
