Repository Sylius/RefundPlugin, pull requests merged in 2023-03, with the labels that each got.

#403 Use sylius_admin.path_name for route prefix
  src/Resources/config/routing.yml
Labels: DX

#406 Make UnitRefundedEventListener listen for all events implementing UnitRefundedInterface
  UPGRADE-1.4.md
  spec/Listener/ShipmentRefundedEventListenerSpec.php
  spec/Listener/UnitRefundedEventListenerSpec.php
  src/Event/ShipmentRefunded.php
  src/Event/UnitRefunded.php
  src/Event/UnitRefundedInterface.php
  src/Listener/ShipmentRefundedEventListener.php
  src/Listener/UnitRefundedEventListener.php
  src/Resources/config/services/event_bus.xml
Labels: Enhancement, DX

#407 Validate if refunded units belong to an order
  UPGRADE-1.4.md
  phpstan.neon
  spec/Validator/OrderItemUnitRefundsBelongingToOrderValidatorSpec.php
  spec/Validator/RefundUnitsCommandValidatorSpec.php
  spec/Validator/ShipmentRefundsBelongingToOrderValidatorSpec.php
  src/Action/Admin/RefundUnitsAction.php
  src/Doctrine/ORM/CountOrderItemUnitRefundsBelongingToOrderQuery.php
  src/Doctrine/ORM/CountRefundsBelongingToOrderQueryInterface.php
  src/Doctrine/ORM/CountShipmentRefundsBelongingToOrderQuery.php
  src/Exception/RefundUnitsNotBelongToOrder.php
  src/Resources/config/services/queries.xml
  src/Resources/config/services/validators.xml
  src/Resources/translations/flashes.en.yml
  src/Validator/OrderItemUnitRefundsBelongingToOrderValidator.php
  src/Validator/RefundUnitsCommandValidator.php
  src/Validator/RefundUnitsValidationConstraintMessages.php
  src/Validator/ShipmentRefundsBelongingToOrderValidator.php
  src/Validator/UnitRefundsBelongingToOrderValidatorInterface.php
Labels: Enhancement

#408 Introduce tags autoconfiguration
  UPGRADE-1.4.md
  src/DependencyInjection/SyliusRefundExtension.php
  src/Provider/OrderItemUnitTotalProvider.php
  src/Provider/RefundUnitTotalProviderInterface.php
  src/Provider/ShipmentTotalProvider.php
  src/Resources/config/services/providers.xml
  tests/DependencyInjection/SyliusRefundExtensionTest.php
Labels: Feature, DX
