Repository Sylius/RefundPlugin, pull requests merged in 2023-02, with the labels that each got.

#395 [Config] Move SyliusTemplateEvents to the separate configuration file
  src/Resources/config/app/config.yml
  src/Resources/config/app/events.yaml
Labels: Feature

#401 [Maintenance] Adjust Messenger env variables
  tests/Application/.env
  tests/Application/.env.test
Labels: Maintenance

#396 `SyliusTemplateEvents` introduced on the `Refund` view
  src/Resources/config/app/events.yaml
  src/Resources/views/Order/Admin/Refund/Button/_clearAll.html.twig
  src/Resources/views/Order/Admin/Refund/Button/_refundAll.html.twig
  src/Resources/views/Order/Admin/Refund/Form/Table/Body/Item/_itemInfo.html.twig
  src/Resources/views/Order/Admin/Refund/Form/Table/Body/Item/_refundButton.html.twig
  src/Resources/views/Order/Admin/Refund/Form/Table/Body/Item/_refundValue.html.twig
  src/Resources/views/Order/Admin/Refund/Form/Table/Body/Item/_total.html.twig
  src/Resources/views/Order/Admin/Refund/Form/Table/Header/_blank.html.twig
  src/Resources/views/Order/Admin/Refund/Form/Table/Header/_itemInfo.html.twig
  src/Resources/views/Order/Admin/Refund/Form/Table/Header/_refundValue.html.twig
  src/Resources/views/Order/Admin/Refund/Form/Table/Header/_total.html.twig
  src/Resources/views/Order/Admin/Refund/Form/Table/_items.html.twig
  src/Resources/views/Order/Admin/Refund/Form/Table/_table.html.twig
  src/Resources/views/Order/Admin/Refund/_buttons.html.twig
  src/Resources/views/Order/Admin/Refund/_comment.html.twig
  src/Resources/views/Order/Admin/Refund/_form.html.twig
  src/Resources/views/Order/Admin/Refund/_navigation.html.twig
  src/Resources/views/Order/Admin/Refund/_paymentMethod.html.twig
  src/Resources/views/Order/Admin/Refund/_refundedTotal.html.twig
  src/Resources/views/_footer.html.twig
  src/Resources/views/_paymentMethod.html.twig
  src/Resources/views/orderRefunds.html.twig
Labels: DX
