Repository Sylius/RefundPlugin, pull requests merged in 2024-12, with the labels that each got.

#454 Add changes to UPGRADE file
  UPGRADE-2.0.md
Labels: Maintenance

#458 Remove partials, add twig components
  config/admin_routing.yml
  config/app/config.yml
  config/app/twig_hooks/admin/order/show.yaml
  config/app/twig_hooks/shop/account/order/show.yaml
  config/services/generators.xml
  config/services/twig_components.xml
  config/shop_routing.yml
  src/Doctrine/ORM/CreditMemoRepository.php
  src/Repository/CreditMemoRepositoryInterface.php
  src/Twig/Component/OrderCreditMemosComponent.php
  templates/Common/Label/refundPaymentState.html.twig
  templates/admin/credit_memo/show/content/sections/memo_details/table/body/net_value.html.twig
  templates/admin/credit_memo/show/list.html.twig
  templates/admin/order/refund/content/sections/form/items/table/body/shipment.html.twig
  templates/download/credit_memo.html.twig
  templates/download/pdf_layout.html.twig
  templates/email/units_refunded.html.twig
  templates/shop/order/_creditMemos.html.twig
  templates/shop/order/credit_memos.html.twig
Labels: Enhancement

#461 SYL-4167: Final hooks refactor
  config/app/twig_hooks/admin/order/show.yaml
  config/app/twig_hooks/shop/account/order/show.yaml
  templates/admin/credit_memo/show/list.html.twig
  templates/admin/order/credit_memo/list.html.twig
  templates/admin/order/credit_memo/list/actions.html.twig
  templates/admin/order/credit_memo/list/channel.html.twig
  templates/admin/order/credit_memo/list/details.html.twig
  templates/admin/order/credit_memo/list/details/date.html.twig
  templates/admin/order/credit_memo/list/details/number.html.twig
  templates/admin/order/credit_memo/list/total.html.twig
  templates/shop/order/credit_memos.html.twig
  templates/shop/order/credit_memos/header.html.twig
  templates/shop/order/credit_memos/list.html.twig
  templates/shop/order/credit_memos/list/details.html.twig
  templates/shop/order/credit_memos/list/details/date.html.twig
  templates/shop/order/credit_memos/list/details/number.html.twig
  templates/shop/order/credit_memos/list/download.html.twig
  templates/shop/order/credit_memos/list/total.html.twig
  templates/shop/order/download_button.html.twig
Labels: Enhancement, DX

#460 [Maintenance] Configuration Files Reorganization and Changing Their Extensions
  README.md
  UPGRADE-2.0.md
  config/config.yaml
  config/integrations.php
  config/routes.yaml
  config/routes/admin.yaml
  config/routes/shop.yaml
  config/twig_hooks/admin/credit_memo/show.yaml
  config/twig_hooks/admin/order/refund/show.yaml
  config/twig_hooks/admin/order/show.yaml
  config/twig_hooks/shop/account/order/show.yaml
  docs/legacy_installation.md
  ecs.php
  phpstan.neon
  tests/Application/config/packages/sylius_refund.yaml
  tests/Application/config/routes.yaml
Labels: Maintenance

#464 Improve Installation Guide
  README.md
  docs/legacy_installation.md
Labels: Maintenance

#465 Add note about Sylius 1.14 in the UPGRADE file
  UPGRADE-1.6.md
Labels: Maintenance
