Repository Sylius/RefundPlugin, pull requests merged in 2024-11, with the labels that each got.

#433 [Maintenance] Support `Sylius v1.14.0-beta.1`
  .github/workflows/build.yml
  composer.json
  src/Provider/RemainingTotalProvider.php
Labels: Maintenance

#438 Add LICENSE_OF_TRADEMARK_AND_LOGO
  LICENSE_OF_TRADEMARK_AND_LOGO
Labels: Maintenance

#436 [Maintenance] Update legacy package.json in test Application
  .github/workflows/build.yml
  composer.json
  tests/Application/package.json
Labels: Maintenance

#440 [Behat] Remove unneeded context
  tests/Behat/Context/Setup/OrderShipmentContext.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites/application/refunds.yaml
  tests/Behat/Resources/suites/ui/refunds.yaml
Labels: Maintenance, Behat

#439 Use StateMachine Abstraction instead of hardcoded Winzou
  UPGRADE-1.6.md
  spec/StateResolver/OrderFullyRefundedStateResolverSpec.php
  spec/StateResolver/OrderPartiallyRefundedStateResolverSpec.php
  spec/StateResolver/RefundPaymentCompletedStateApplierSpec.php
  src/Resources/config/services/state_resolvers.xml
  src/StateResolver/OrderFullyRefundedStateResolver.php
  src/StateResolver/OrderPartiallyRefundedStateResolver.php
  src/StateResolver/RefundPaymentCompletedStateApplier.php
Labels: Bug, Maintenance

#441 [CI] Update builds' matrix
  .github/workflows/build.yml
Labels: Maintenance

#442 [Behat] Use Chrome instead of Selenium driver
  CONFLICTS.md
  behat.yml.dist
  composer.json
Labels: Behat, Dependencies

#447 Rename and deprecate parameters
  UPGRADE-1.6.md
  src/Resources/config/app/config.yml
  src/Resources/config/services.xml
  src/Resources/config/services/generators.xml
Labels: Maintenance

#445 Regenerate migrations
  UPGRADE-2.0.md
  src/Migrations/Version20180703112314.php
  src/Migrations/Version20180704112314.php
  src/Migrations/Version20180718125528.php
  src/Migrations/Version20180817130113.php
  src/Migrations/Version20180820132147.php
  src/Migrations/Version20180829090832.php
  src/Migrations/Version20190207125150.php
  src/Migrations/Version20190215154028.php
  src/Migrations/Version20190517064223.php
  src/Migrations/Version20190928200659.php
  src/Migrations/Version20191217075815.php
  src/Migrations/Version20191230121402.php
  src/Migrations/Version20200113091731.php
  src/Migrations/Version20200125182414.php
  src/Migrations/Version20200131082149.php
  src/Migrations/Version20200304172851.php
  src/Migrations/Version20200306145439.php
  src/Migrations/Version20200306153205.php
  src/Migrations/Version20200310094633.php
  src/Migrations/Version20200310185620.php
  src/Migrations/Version20210608074013.php
  src/Migrations/Version20210609071246.php
Labels: Maintenance

#449 [CI] Remove unneeded build + minor improvements
  .github/workflows/build.yaml
Labels: Maintenance

#448 Replace deprecated services' names and parameters + minor clean up
  CHANGELOG-1.0.md
  CHANGELOG-1.1.md
  CHANGELOG-1.2.md
  CHANGELOG-1.3.md
  CHANGELOG-1.4.md
  CHANGELOG-1.5.md
  UPGRADE-1.0.md
  UPGRADE-1.1.md
  UPGRADE-1.2.md
  UPGRADE-1.3.md
  UPGRADE-1.4.md
  UPGRADE-1.5.md
  UPGRADE-1.6.md
  UPGRADE-2.0.md
  src/DependencyInjection/Configuration.php
  src/Resources/config/app/config.yml
  src/Resources/config/services.xml
  src/Resources/config/services/actions.xml
  src/Resources/config/services/checkers.xml
  src/Resources/config/services/command_bus.xml
  src/Resources/config/services/converters.xml
  src/Resources/config/services/creators.xml
  src/Resources/config/services/event_bus.xml
  src/Resources/config/services/factories.xml
  src/Resources/config/services/filters.xml
  src/Resources/config/services/generators.xml
  src/Resources/config/services/listeners.xml
  src/Resources/config/services/providers.xml
  src/Resources/config/services/queries.xml
  src/Resources/config/services/resolvers.xml
  src/Resources/config/services/state_resolvers.xml
  src/Resources/config/services/validators.xml
Labels: Maintenance

#450 Move StateMachineAbstraction config to the proper directory in the test application
  tests/Application/config/packages/sylius_state_machine_abstraction.yaml
Labels: Maintenance

#453 Update legacy installation instructions
  docs/legacy_installation.md
Labels: Maintenance
